/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.c308team2.parkinglotapp;

import java.awt.CardLayout;
import javax.swing.JPanel;


public class ParkingListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ParkingListPanel
     */
    public ParkingListPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        parkingLotList = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(1080, 720));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1080, 720));

        parkingLotList.setModel(Database.lotDB);
        parkingLotList.setCellRenderer(new ParkingLotCellRenderer());
        parkingLotList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                parkingLotListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(parkingLotList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void parkingLotListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_parkingLotListValueChanged
        // method called when a ParkingLot is selected from the list
        
        // get selected lot
        ParkingLot currentLot = parkingLotList.getSelectedValue();
        
        // get lotPanel, this is the panel that displays individual lot info
        ParkingLotPanel lotPanel = (ParkingLotPanel) getParent().getComponent(1);
        // update lotPanel with selected lot
        if(currentLot != null) lotPanel.updateLot(currentLot);
        
        // show the lotPanel card
        CardLayout card = (CardLayout) getParent().getLayout();
        card.show(getParent(), "lotCard");
        
        // clear selection
        parkingLotList.clearSelection();
    }//GEN-LAST:event_parkingLotListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<ParkingLot> parkingLotList;
    // End of variables declaration//GEN-END:variables
}
