/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.c308team2.parkinglotapp;

import java.awt.Color;

/**
 *
 * @author dustt
 */
public class ParkingListItem extends javax.swing.JPanel {

    /**
     * Creates new form ParkingListItem
     */
    public ParkingListItem() {
        initComponents();
    }
    
    public ParkingListItem(ParkingLot parkingLot){
        initComponents();
        lotNameLabel.setText(parkingLot.getLotName());
        lotAddressLabel.setText(parkingLot.getAddress());
        numberSpacesLabel.setText(parkingLot.getEmptySpaces() + " / " + parkingLot.getTotalSpaces());
        progressBar.setMaximum(parkingLot.getTotalSpaces());
        progressBar.setValue(parkingLot.getOccupiedSpaces());
        double fullness = parkingLot.getOccupiedSpaces() / (1.0 * parkingLot.getTotalSpaces());
        if(fullness == 1) progressBar.setForeground(Color.red);
        else if(fullness >= 0.60) progressBar.setForeground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lotNameLabel = new javax.swing.JLabel();
        lotAddressLabel = new javax.swing.JLabel();
        availableSpacesLabel = new javax.swing.JLabel();
        numberSpacesLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1080, 150));
        setPreferredSize(new java.awt.Dimension(1000, 150));

        lotNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lotNameLabel.setText("Lot Name");

        lotAddressLabel.setText("Lot Address");

        availableSpacesLabel.setText("Available Spaces:");

        numberSpacesLabel.setText("-- / --");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lotNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addComponent(lotAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(availableSpacesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(numberSpacesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availableSpacesLabel)
                    .addComponent(lotNameLabel))
                .addGap(10, 10, 10)
                .addComponent(numberSpacesLabel)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lotAddressLabel))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableSpacesLabel;
    private javax.swing.JLabel lotAddressLabel;
    private javax.swing.JLabel lotNameLabel;
    private javax.swing.JLabel numberSpacesLabel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
